"""M2 — the canon-declared entry point file exists on disk.

Reads ``canon.identity.entry_point`` (default ``"MYCO.md"``) and
confirms a file at that substrate-relative path exists. A missing
entry-point file breaks the boot-brief contract (ingestion/hunger
reads it) and leaves agents without a reliable anchor page.

Severity: HIGH.

v0.5.5 — **fixable**. ``myco immune --fix`` creates the missing
entry-point file with a minimal skeleton pointing the agent at
``_canon.yaml``, ``docs/architecture/``, and ``docs/primordia/``.
The fix never overwrites a non-empty file and is idempotent: a
second ``--fix`` pass is a silent no-op.
"""

from __future__ import annotations

from collections.abc import Iterable
from datetime import timezone
from string import Template
from typing import Any, ClassVar

from myco.core.context import MycoContext
from myco.core.io_atomic import atomic_utf8_write
from myco.core.severity import Severity

from ..dimension import Dimension
from ..finding import Category, Finding

__all__ = ["M2EntryPointExists"]


_ENTRY_POINT_TEMPLATE = Template(
    "# $substrate_id \u2014 Myco substrate\n"
    "\n"
    "This is the agent entry point for the `$substrate_id` substrate.\n"
    "See `_canon.yaml` for contract, `docs/architecture/` for doctrine,\n"
    "`docs/primordia/` for craft history.\n"
    "\n"
    "Generated by `myco immune --fix` on $generated_at.\n"
)


class M2EntryPointExists(Dimension):
    """Canon entry-point file must exist under the substrate root."""

    id = "M2"
    category = Category.MECHANICAL
    default_severity = Severity.HIGH

    #: v0.5.5 — M2 autonomously creates the missing entry-point file
    #: from a minimal skeleton template. See :meth:`fix`.
    fixable: ClassVar[bool] = True

    def run(self, ctx: MycoContext) -> Iterable[Finding]:
        entry = ctx.substrate.canon.entry_point  # defaults to "MYCO.md"
        if not entry:
            return
        path = ctx.substrate.root / entry
        if not path.is_file():
            yield Finding(
                dimension_id=self.id,
                category=self.category,
                severity=self.default_severity,
                message=(
                    f"entry point {entry!r} declared in canon "
                    f"but no file found at that path"
                ),
                path=entry,
            )

    def fix(self, ctx: MycoContext, finding: Finding) -> dict[str, Any]:
        """Create the missing entry-point file from a skeleton template.

        Idempotent + narrow contract (v0.5.5):

        - If the target file already exists and is non-empty, the fix
          is a silent no-op (``applied=False``, descriptive detail).
        - Creates parent directories if they don't exist (the entry
          point usually sits at substrate root, but a canon that
          points it at a subdirectory is legal).
        - Writes atomically via a single ``write_text`` — the file is
          too small to need temp-file-plus-rename semantics.
        - Never touches anything else.

        The write-surface guard in
        :func:`myco.homeostasis.kernel._apply_fix` has already run by
        the time we get here, so the target is known-safe.
        """
        entry = ctx.substrate.canon.entry_point
        if not entry:
            return {
                "applied": False,
                "detail": "canon declares no entry_point; nothing to fix",
            }

        target = ctx.substrate.root / entry
        if target.is_file() and target.stat().st_size > 0:
            # Idempotent: a second --fix pass sees the file we wrote
            # last time (or one the user populated themselves) and
            # refuses to overwrite it.
            return {
                "applied": False,
                "detail": f"entry point {entry!r} already exists; not overwriting",
            }

        substrate_id = ctx.substrate.canon.substrate_id or "unnamed"
        generated_at = ctx.now.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        body = _ENTRY_POINT_TEMPLATE.substitute(
            substrate_id=substrate_id,
            generated_at=generated_at,
        )

        atomic_utf8_write(target, body)
        return {
            "applied": True,
            "detail": f"created entry point {entry!r} ({len(body)} bytes)",
        }
