"""scaffold verb: generate a handler stub from the manifest.

MAJOR 10 (v0.5): closes the "adding a verb requires a hand-written
handler module" gap. Given a verb name already present in
``src/myco/surface/manifest.yaml``, writes a minimal handler stub at
the filesystem path derived from the verb's ``handler:`` string.

The stub returns a well-formed ``Result`` with
``payload.stub = True`` and an exit code of ``0`` so the immune
kernel's ``test_every_handler_resolves`` gate stays green while the
agent fleshes out the real implementation. The stub also raises a
``DeprecationWarning`` on invocation so a run against an
unfinished verb is loud rather than silently trivial.

Usage::

    # Assume manifest has a verb `foo` with handler `myco.ingestion.foo:run`.
    myco scaffold --verb foo
    # → writes src/myco/ingestion/foo.py (creates parents if needed)

    myco scaffold --verb foo --force
    # → overwrites existing src/myco/ingestion/foo.py

Refuses to scaffold a verb that does not exist in the manifest —
editing the manifest first is the intended order (manifest is
SSoT). Refuses to overwrite unless ``--force`` is passed.

Governing doctrine: ``docs/architecture/L2_DOCTRINE/surface.md``
(governance-verbs appendix, v0.5).
"""

from __future__ import annotations

from pathlib import Path
from typing import Mapping

from myco.core.context import MycoContext, Result
from myco.core.errors import ContractError, UsageError
from myco.surface.manifest import load_manifest

__all__ = ["run"]


_STUB_TEMPLATE = '''\
"""{verb} verb — stub handler generated by `myco scaffold`.

TODO: replace this body with the real implementation. Every call
currently returns exit 0 with ``payload.stub = True`` and emits a
DeprecationWarning so unfinished verbs are not silently benign.

Manifest entry: src/myco/surface/manifest.yaml ("{verb}")
Handler contract:
    def run(args: Mapping[str, object], *, ctx: MycoContext) -> Result
"""

from __future__ import annotations

import warnings
from typing import Mapping

from myco.core.context import MycoContext, Result

__all__ = ["run"]


def run(args: Mapping[str, object], *, ctx: MycoContext) -> Result:  # noqa: D401, ARG001
    warnings.warn(
        "myco {verb}: this is a scaffold stub generated by "
        "`myco scaffold`; it has not been implemented yet.",
        DeprecationWarning,
        stacklevel=2,
    )
    return Result(
        exit_code=0,
        payload={{
            "stub": True,
            "verb": "{verb}",
            "message": "handler not yet implemented",
        }},
    )
'''


def _handler_path(handler: str, substrate_root: Path) -> Path:
    """Turn ``"myco.ingestion.foo:run"`` into ``<root>/src/myco/ingestion/foo.py``."""
    if ":" not in handler:
        raise ContractError(
            f"scaffold: handler {handler!r} must be 'module:function'"
        )
    module_path, _func = handler.split(":", 1)
    parts = module_path.split(".")
    return substrate_root.joinpath("src", *parts).with_suffix(".py")


def run(args: Mapping[str, object], *, ctx: MycoContext) -> Result:
    verb = args.get("verb")
    if not verb:
        raise UsageError("scaffold: --verb <name> is required")
    verb_name = str(verb).strip()
    force = bool(args.get("force", False))

    manifest = load_manifest()
    try:
        spec = manifest.by_name(verb_name)
    except UsageError:
        raise UsageError(
            f"scaffold: verb {verb_name!r} is not declared in manifest.yaml. "
            f"Edit the manifest first (manifest is SSoT)."
        )

    target = _handler_path(spec.handler, ctx.substrate.root)

    already_exists = target.exists()
    if already_exists and not force:
        return Result(
            exit_code=0,
            payload={
                "verb": verb_name,
                "handler": spec.handler,
                "path": str(target.relative_to(ctx.substrate.root)
                            if target.is_relative_to(ctx.substrate.root)
                            else target),
                "written": False,
                "reason": "handler file already exists; pass --force to overwrite",
            },
        )

    target.parent.mkdir(parents=True, exist_ok=True)
    stub = _STUB_TEMPLATE.format(verb=verb_name)
    target.write_text(stub, encoding="utf-8")

    return Result(
        exit_code=0,
        payload={
            "verb": verb_name,
            "handler": spec.handler,
            "path": str(target.relative_to(ctx.substrate.root)
                        if target.is_relative_to(ctx.substrate.root)
                        else target),
            "written": True,
            "overwritten": already_exists,
        },
    )
