"""
Myco Session-End Hook — Zero-touch close-out ritual.

Wave 56 (vision_closure_craft_2026-04-14.md Wave 1):
  When a session ends, automate:
    1. Auto-eat the session summary (if provided) as a raw note
    2. Prune --auto: excrete obvious dead-knowledge notes
    3. Refresh .myco_state/boot_brief.md so next session opens hot

Callable two ways:
  - Explicit MCP tool: myco_session_end(summary=..., project_dir=...)
  - Host adapter hook: hosts/{cowork,claude_code}.py can invoke on exit
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def run_session_end(
    root: Path,
    *,
    summary: Optional[str] = None,
    prune: bool = True,
    refresh_brief: bool = True,
) -> dict:
    """Execute session-end ritual. Never raises; returns a status dict."""
    root = Path(root).resolve()
    result = {
        "ok": True,
        "ate": None,
        "pruned": 0,
        "brief_refreshed": False,
        "errors": [],
    }

    if not (root / "_canon.yaml").exists():
        result["ok"] = False
        result["errors"].append("not a Myco project")
        return result

    # 1. Auto-eat summary
    if summary and summary.strip():
        try:
            from myco.notes import write_note
            path = write_note(
                root,
                summary,
                tags=["session-end", "auto"],
                source="chat",
                status="raw",
                title=f"Session summary {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')}",
            )
            result["ate"] = str(path.relative_to(root))
        except Exception as e:
            result["errors"].append(f"eat: {e}")

    # 2. Auto-prune (conservative: auto=True only excretes 2+-rule matches)
    if prune:
        try:
            from myco.notes import auto_excrete_multipath_candidates
            pruned = auto_excrete_multipath_candidates(
                root, auto=True, dry_run=False,
            )
            if pruned:
                result["pruned"] = sum(1 for p in pruned if p.get("applied"))
        except Exception as e:
            result["errors"].append(f"prune: {e}")

    # 3. Refresh boot brief
    if refresh_brief:
        try:
            _refresh_boot_brief(root)
            result["brief_refreshed"] = True
        except Exception as e:
            result["errors"].append(f"brief: {e}")

    # 4. Log metabolism tick (best-effort — signature matches compute_hunger output)
    try:
        from myco.metabolism import log_metabolism
        log_metabolism(root, {
            "event": "session_end",
            "total": 0,
            "by_status": {},
            "signals": [],
            "deep_digested": [],
            "dead_notes": [],
            "ate": bool(result["ate"]),
            "pruned": result["pruned"],
        })
    except Exception:
        pass  # metabolism module may not be present on old installs

    return result


def _refresh_boot_brief(root: Path) -> None:
    """Regenerate .myco_state/boot_brief.md from current hunger signals."""
    try:
        from myco.immune import main as immune_main  # noqa: F401
    except Exception:
        pass

    # Cheap reconstruction: collect quick hunger-like signals.
    notes_dir = root / "notes"
    raw_count = 0
    if notes_dir.is_dir():
        for f in notes_dir.glob("n_*.md"):
            head = f.read_text(encoding="utf-8", errors="replace")[:300]
            if "status: raw" in head:
                raw_count += 1

    brief_dir = root / ".myco_state"
    brief_dir.mkdir(parents=True, exist_ok=True)
    brief = brief_dir / "boot_brief.md"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# Boot Brief — {now}",
        "",
        "Auto-generated by session_hook.run_session_end.",
        "",
        "## Signals",
        "",
    ]
    if raw_count > 0:
        lines.append(f"- • raw notes pending digestion: {raw_count}")
    else:
        lines.append("- • substrate healthy")
    lines.append("")
    lines.append("## Next-action hint")
    lines.append("")
    if raw_count > 3:
        lines.append(f"Call `myco_digest` on the {raw_count} raw notes.")
    else:
        lines.append("Call `myco_hunger(execute=true)` to refresh full dashboard.")
    lines.append("")
    brief.write_text("\n".join(lines), encoding="utf-8")
