"""ramify verb: scaffold a new verb / dimension / adapter.

Governing doctrine: ``docs/architecture/L2_DOCTRINE/surface.md``
(governance-verbs appendix). Governing craft:
``docs/primordia/v0_5_3_fungal_vocabulary_craft_2026-04-17.md``
(MAJOR 10 — the substrate-local extension seam).

ramify is the kernel's equivalent of hyphal branching: it extrudes a
new leaf module from the existing tree. Three modes:

1. ``--verb <name>`` — legacy scaffold (v0.5.0): writes a handler stub
   for a manifest-declared verb. Default target is
   ``src/myco/<subsystem>/<verb>.py`` when running against myco-self;
   otherwise writes under ``.myco/plugins/handlers/<verb>.py`` AND
   appends an entry to ``.myco/manifest_overlay.yaml``.

2. ``--dimension <id> --category <cat> --severity <sev>`` — scaffold
   a lint :class:`Dimension` subclass. Kernel-mode target is
   ``src/myco/homeostasis/dimensions/<id_lower>_<slug>.py``; substrate-
   local target is ``.myco/plugins/dimensions/<id_lower>.py`` plus
   autowiring of ``.myco/plugins/__init__.py`` to call
   :func:`register_external_dimension`.

3. ``--adapter <name> --extensions <e1,e2,...>`` — scaffold an
   ingestion Adapter class. Kernel-mode target is
   ``src/myco/ingestion/adapters/<name>.py``; substrate-local target
   is ``.myco/plugins/adapters/<name>.py``.

The ``--substrate-local`` flag overrides autodetection. The
autodetection rule: substrate-local mode is ON by default when the
substrate_id is NOT ``myco-self`` OR when ``<root>/src/myco/`` does
not exist. This preserves the v0.5.0 scaffold behavior for Myco-self
while giving downstream substrates a frictionless path.
"""

from __future__ import annotations

from pathlib import Path
from typing import Mapping

import yaml

from myco.core.context import MycoContext, Result
from myco.core.errors import ContractError, UsageError
from myco.surface.manifest import load_manifest

__all__ = ["run"]


# -------- verb-mode stub template (kept word-for-word compatible with
#          v0.5.0 tests that grep for "stub handler generated by").

_VERB_STUB_TEMPLATE = '''\
"""{verb} verb — stub handler generated by `myco scaffold`.

TODO: replace this body with the real implementation. Every call
currently returns exit 0 with ``payload.stub = True`` and emits a
DeprecationWarning so unfinished verbs are not silently benign.

Manifest entry: src/myco/surface/manifest.yaml ("{verb}")
Handler contract:
    def run(args: Mapping[str, object], *, ctx: MycoContext) -> Result
"""

from __future__ import annotations

import warnings
from typing import Mapping

from myco.core.context import MycoContext, Result

__all__ = ["run"]


def run(args: Mapping[str, object], *, ctx: MycoContext) -> Result:  # noqa: D401, ARG001
    warnings.warn(
        "myco {verb}: this is a scaffold stub generated by "
        "`myco scaffold`; it has not been implemented yet.",
        DeprecationWarning,
        stacklevel=2,
    )
    return Result(
        exit_code=0,
        payload={{
            "stub": True,
            "verb": "{verb}",
            "message": "handler not yet implemented",
        }},
    )
'''


# -------- dimension-mode stub template.

_DIMENSION_STUB_TEMPLATE = '''\
"""{dim_id} — stub dimension generated by `myco ramify`.

TODO: replace ``run`` with a real check. This stub yields no findings
so it is a no-op on the immune kernel; the class is wired to register
automatically via ``register_external_dimension`` in substrate-local
mode, or via ``pyproject.toml``'s ``myco.dimensions`` entry-point in
kernel mode.

Fungal-vocabulary scaffold: this file was extruded from the kernel's
hyphal tip (``myco ramify``). See
``docs/primordia/v0_5_3_fungal_vocabulary_craft_2026-04-17.md``.
"""

from __future__ import annotations

from typing import Iterable

from myco.core.context import MycoContext
from myco.core.severity import Severity

from myco.homeostasis.dimension import Dimension
from myco.homeostasis.finding import Category, Finding

__all__ = ["{class_name}"]


class {class_name}(Dimension):
    """TODO: one-line description of what this dimension checks."""

    id = "{dim_id}"
    category = Category.{category_const}
    default_severity = Severity.{severity_const}

    def run(self, ctx: MycoContext) -> Iterable[Finding]:
        # TODO: implement the check. Yield ``Finding`` objects for any
        # problems detected. Currently yields nothing (no-op stub).
        if False:
            yield Finding(
                dimension_id=self.id,
                category=self.category,
                severity=self.default_severity,
                message="stub",
            )
'''


# -------- adapter-mode stub template.

_ADAPTER_STUB_TEMPLATE = '''\
"""{class_name} — stub adapter generated by `myco ramify`.

TODO: replace ``ingest`` with real extraction. Handles files with any
of the declared ``extensions``. Currently returns a single-note
``IngestResult`` containing the file's raw text.

Fungal-vocabulary scaffold: see
``docs/primordia/v0_5_3_fungal_vocabulary_craft_2026-04-17.md``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from myco.ingestion.adapters.protocol import Adapter, IngestResult

__all__ = ["{class_name}"]


class {class_name}:
    """TODO: describe what this adapter ingests."""

    name = "{adapter_name}"
    extensions = ({extensions_tuple})

    def can_handle(self, target: str) -> bool:
        t = target.lower()
        return any(t.endswith(ext) for ext in self.extensions)

    def ingest(self, target: str) -> Iterable[IngestResult]:
        path = Path(target)
        text = path.read_text(encoding="utf-8", errors="replace")
        yield IngestResult(
            source=str(path),
            text=text,
            tags=(self.name,),
        )
'''


# -------- plugin __init__.py autoloader (substrate-local).

_PLUGIN_INIT_TEMPLATE = '''\
"""Substrate-local Myco plugin package.

Generated by `myco ramify`. Imports dimension + adapter subpackages so
their registration side-effects fire at Substrate.load() time.

Fungal-vocabulary craft:
``docs/primordia/v0_5_3_fungal_vocabulary_craft_2026-04-17.md``.
"""

from __future__ import annotations

# Best-effort import of subpackages. A missing subpackage is fine —
# only the ones we have get loaded.
try:
    from . import dimensions as _dimensions  # noqa: F401
except Exception:
    pass

try:
    from . import adapters as _adapters  # noqa: F401
except Exception:
    pass

try:
    from . import handlers as _handlers  # noqa: F401
except Exception:
    pass
'''


_DIMENSIONS_PKG_INIT = '''\
"""Substrate-local dimensions subpackage. Side-effect imports below
register every module via ``register_external_dimension``."""

from __future__ import annotations

import importlib
import pkgutil

from myco.homeostasis.registry import register_external_dimension

__all__ = ["register_all"]


def register_all() -> None:
    """Walk this subpackage and register every ``Dimension`` subclass."""
    for mod_info in pkgutil.iter_modules(__path__):  # type: ignore[name-defined]
        mod = importlib.import_module(f"{{__name__}}.{{mod_info.name}}")
        for obj in vars(mod).values():
            if isinstance(obj, type):
                try:
                    register_external_dimension(obj)
                except TypeError:
                    continue


register_all()
'''


_ADAPTERS_PKG_INIT = '''\
"""Substrate-local adapters subpackage. Side-effect imports below
register every module via ``myco.ingestion.adapters.register``."""

from __future__ import annotations

import importlib
import pkgutil

from myco.ingestion.adapters import register as _register_adapter

__all__ = ["register_all"]


def register_all() -> None:
    """Walk this subpackage and register every adapter class instance."""
    for mod_info in pkgutil.iter_modules(__path__):  # type: ignore[name-defined]
        mod = importlib.import_module(f"{{__name__}}.{{mod_info.name}}")
        for obj in vars(mod).values():
            if isinstance(obj, type) and hasattr(obj, "can_handle") and hasattr(obj, "ingest"):
                try:
                    _register_adapter(obj())
                except Exception:
                    continue


register_all()
'''


# -------- helpers


_CATEGORY_CONSTS = {
    "mechanical": "MECHANICAL",
    "shipped": "SHIPPED",
    "metabolic": "METABOLIC",
    "semantic": "SEMANTIC",
}

_SEVERITY_CONSTS = {
    "low": "LOW",
    "medium": "MEDIUM",
    "high": "HIGH",
    "critical": "CRITICAL",
}


def _slug(raw: str) -> str:
    out = []
    for ch in raw.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in "-_ ":
            out.append("_")
    slug = "".join(out).strip("_")
    return slug or "x"


def _handler_path(handler: str, substrate_root: Path) -> Path:
    """Turn ``"myco.ingestion.foo:run"`` into ``<root>/src/myco/ingestion/foo.py``."""
    if ":" not in handler:
        raise ContractError(
            f"scaffold: handler {handler!r} must be 'module:function'"
        )
    module_path, _func = handler.split(":", 1)
    parts = module_path.split(".")
    return substrate_root.joinpath("src", *parts).with_suffix(".py")


def _detect_substrate_local(
    ctx: MycoContext, explicit: object, *, mode: str
) -> bool:
    """Decide whether ramify should write under ``.myco/plugins/``.

    ``mode`` is one of ``"verb"``, ``"dimension"``, ``"adapter"``.

    - Explicit True (CLI ``--substrate-local``) → always True.
    - Explicit False with ``verb`` mode → False (preserves the
      pre-v0.5.3 ``myco scaffold --verb`` behavior for every test
      substrate, including non-myco-self). Scaffold tests from
      v0.5.0 that did not pass ``--substrate-local`` continue to see
      the kernel-mode path.
    - Explicit False with ``dimension``/``adapter`` mode →
      autodetect (substrate-local when substrate_id != "myco-self"
      OR ``<root>/src/myco/`` is missing). These are new modes at
      v0.5.3 so there is no legacy kernel-mode expectation to honor.
    """
    if explicit is True or explicit == "true":
        return True

    if mode == "verb":
        # Preserve v0.5.0 scaffold default: kernel mode unless asked.
        return False

    # Dimension/adapter modes: autodetect.
    sid = (ctx.substrate.canon.substrate_id or "").strip()
    if sid != "myco-self":
        return True
    kernel_src = ctx.substrate.root / "src" / "myco"
    if not kernel_src.is_dir():
        return True
    return False


def _ensure_pkg(dir_path: Path, init_body: str | None = None) -> None:
    dir_path.mkdir(parents=True, exist_ok=True)
    init = dir_path / "__init__.py"
    if not init.exists():
        init.write_text(init_body or "", encoding="utf-8")


def _ensure_plugin_tree(ctx: MycoContext, kind: str) -> Path:
    """Ensure ``.myco/plugins/`` + the relevant subpackage exists.

    ``kind`` is one of ``"dimensions"``, ``"adapters"``, ``"handlers"``.
    Returns the absolute path to the subpackage directory.
    """
    root = ctx.substrate.root
    plugins = root / ".myco" / "plugins"
    _ensure_pkg(plugins, _PLUGIN_INIT_TEMPLATE)

    sub = plugins / kind
    if kind == "dimensions":
        _ensure_pkg(sub, _DIMENSIONS_PKG_INIT)
    elif kind == "adapters":
        _ensure_pkg(sub, _ADAPTERS_PKG_INIT)
    else:
        _ensure_pkg(sub, "")
    return sub


def _append_overlay_verb(
    ctx: MycoContext,
    *,
    verb: str,
    subsystem: str,
    handler: str,
    summary: str,
    mcp_tool: str,
) -> Path:
    """Create or append to ``.myco/manifest_overlay.yaml`` for a new verb."""
    overlay_path = ctx.substrate.paths.manifest_overlay
    overlay_path.parent.mkdir(parents=True, exist_ok=True)

    if overlay_path.exists():
        raw = yaml.safe_load(overlay_path.read_text(encoding="utf-8")) or {}
        if not isinstance(raw, dict):
            raise ContractError(
                f"ramify: existing manifest overlay is not a mapping: {overlay_path}"
            )
    else:
        raw = {"schema_version": "1", "commands": []}

    commands = raw.setdefault("commands", [])
    if not isinstance(commands, list):
        raise ContractError(
            "ramify: manifest overlay commands must be a list"
        )
    # Refuse to duplicate.
    for entry in commands:
        if isinstance(entry, dict) and entry.get("name") == verb:
            return overlay_path
    commands.append(
        {
            "name": verb,
            "subsystem": subsystem,
            "handler": handler,
            "summary": summary,
            "mcp_tool": mcp_tool,
            "args": [],
        }
    )
    overlay_path.write_text(
        yaml.safe_dump(raw, sort_keys=False), encoding="utf-8"
    )
    return overlay_path


# -------- mode handlers


def _run_verb_mode(
    args: Mapping[str, object], ctx: MycoContext, substrate_local: bool, force: bool
) -> Result:
    verb_name = str(args["verb"]).strip()
    manifest = load_manifest()
    try:
        spec = manifest.by_name(verb_name)
    except UsageError:
        raise UsageError(
            f"scaffold: verb {verb_name!r} is not declared in manifest.yaml. "
            f"Edit the manifest first (manifest is SSoT)."
        )

    overlay_updated = False
    if substrate_local:
        # Substrate-local handler goes under .myco/plugins/handlers/.
        handlers_dir = _ensure_plugin_tree(ctx, "handlers")
        target = handlers_dir / f"{verb_name}.py"
    else:
        target = _handler_path(spec.handler, ctx.substrate.root)

    already_exists = target.exists()
    if already_exists and not force:
        return Result(
            exit_code=0,
            payload={
                "mode": "verb",
                "verb": verb_name,
                "handler": spec.handler,
                "path": str(
                    target.relative_to(ctx.substrate.root)
                    if target.is_relative_to(ctx.substrate.root)
                    else target
                ),
                "written": False,
                "substrate_local": substrate_local,
                "reason": "handler file already exists; pass --force to overwrite",
            },
        )

    target.parent.mkdir(parents=True, exist_ok=True)
    stub = _VERB_STUB_TEMPLATE.format(verb=verb_name)
    target.write_text(stub, encoding="utf-8")

    if substrate_local:
        # Wire the overlay so the verb is invokable without a pyproject change.
        _append_overlay_verb(
            ctx,
            verb=verb_name,
            subsystem=spec.subsystem,
            handler=f"plugins.handlers.{verb_name}:run",
            summary=spec.summary,
            mcp_tool=spec.mcp_tool,
        )
        overlay_updated = True

    return Result(
        exit_code=0,
        payload={
            "mode": "verb",
            "verb": verb_name,
            "handler": spec.handler,
            "path": str(
                target.relative_to(ctx.substrate.root)
                if target.is_relative_to(ctx.substrate.root)
                else target
            ),
            "written": True,
            "overwritten": already_exists,
            "substrate_local": substrate_local,
            "overlay_updated": overlay_updated,
        },
    )


def _run_dimension_mode(
    args: Mapping[str, object], ctx: MycoContext, substrate_local: bool, force: bool
) -> Result:
    dim_id = str(args["dimension"]).strip()
    category = str(args.get("category") or "").strip().lower()
    severity = str(args.get("severity") or "").strip().lower()
    if not category:
        raise UsageError("ramify: --dimension requires --category")
    if not severity:
        raise UsageError("ramify: --dimension requires --severity")
    if category not in _CATEGORY_CONSTS:
        raise UsageError(
            f"ramify: unknown category {category!r}; expected one of "
            f"{sorted(_CATEGORY_CONSTS)}"
        )
    if severity not in _SEVERITY_CONSTS:
        raise UsageError(
            f"ramify: unknown severity {severity!r}; expected one of "
            f"{sorted(_SEVERITY_CONSTS)}"
        )

    slug = _slug(dim_id)
    class_name = "".join(part.capitalize() for part in slug.split("_")) + "Dimension"
    if not class_name[:1].isalpha():
        class_name = "D" + class_name

    if substrate_local:
        sub = _ensure_plugin_tree(ctx, "dimensions")
        target = sub / f"{slug}.py"
    else:
        target = (
            ctx.substrate.root
            / "src"
            / "myco"
            / "homeostasis"
            / "dimensions"
            / f"{slug}.py"
        )

    already_exists = target.exists()
    if already_exists and not force:
        return Result(
            exit_code=0,
            payload={
                "mode": "dimension",
                "dimension": dim_id,
                "path": str(
                    target.relative_to(ctx.substrate.root)
                    if target.is_relative_to(ctx.substrate.root)
                    else target
                ),
                "written": False,
                "substrate_local": substrate_local,
                "reason": "dimension file already exists; pass --force to overwrite",
            },
        )

    target.parent.mkdir(parents=True, exist_ok=True)
    body = _DIMENSION_STUB_TEMPLATE.format(
        dim_id=dim_id,
        class_name=class_name,
        category_const=_CATEGORY_CONSTS[category],
        severity_const=_SEVERITY_CONSTS[severity],
    )
    target.write_text(body, encoding="utf-8")

    return Result(
        exit_code=0,
        payload={
            "mode": "dimension",
            "dimension": dim_id,
            "class": class_name,
            "category": category,
            "severity": severity,
            "path": str(
                target.relative_to(ctx.substrate.root)
                if target.is_relative_to(ctx.substrate.root)
                else target
            ),
            "written": True,
            "overwritten": already_exists,
            "substrate_local": substrate_local,
        },
    )


def _run_adapter_mode(
    args: Mapping[str, object], ctx: MycoContext, substrate_local: bool, force: bool
) -> Result:
    adapter_name = str(args["adapter"]).strip()
    extensions = args.get("extensions") or ()
    if isinstance(extensions, str):
        extensions = (extensions,)
    extensions = tuple(str(e).strip() for e in extensions if str(e).strip())
    if not extensions:
        raise UsageError(
            "ramify: --adapter requires --extensions (e.g. --extensions .json,.csv)"
        )
    # Normalize extensions to lead with ".".
    norm_exts = tuple(
        e if e.startswith(".") else f".{e}" for e in extensions
    )

    slug = _slug(adapter_name)
    class_name = "".join(p.capitalize() for p in slug.split("_")) + "Adapter"
    if not class_name[:1].isalpha():
        class_name = "A" + class_name

    if substrate_local:
        sub = _ensure_plugin_tree(ctx, "adapters")
        target = sub / f"{slug}.py"
    else:
        target = (
            ctx.substrate.root
            / "src"
            / "myco"
            / "ingestion"
            / "adapters"
            / f"{slug}.py"
        )

    already_exists = target.exists()
    if already_exists and not force:
        return Result(
            exit_code=0,
            payload={
                "mode": "adapter",
                "adapter": adapter_name,
                "path": str(
                    target.relative_to(ctx.substrate.root)
                    if target.is_relative_to(ctx.substrate.root)
                    else target
                ),
                "written": False,
                "substrate_local": substrate_local,
                "reason": "adapter file already exists; pass --force to overwrite",
            },
        )

    target.parent.mkdir(parents=True, exist_ok=True)
    body = _ADAPTER_STUB_TEMPLATE.format(
        class_name=class_name,
        adapter_name=adapter_name,
        extensions_tuple=", ".join(repr(e) for e in norm_exts)
        + ("," if len(norm_exts) == 1 else ""),
    )
    target.write_text(body, encoding="utf-8")

    return Result(
        exit_code=0,
        payload={
            "mode": "adapter",
            "adapter": adapter_name,
            "class": class_name,
            "extensions": list(norm_exts),
            "path": str(
                target.relative_to(ctx.substrate.root)
                if target.is_relative_to(ctx.substrate.root)
                else target
            ),
            "written": True,
            "overwritten": already_exists,
            "substrate_local": substrate_local,
        },
    )


def run(args: Mapping[str, object], *, ctx: MycoContext) -> Result:
    verb = args.get("verb")
    dimension = args.get("dimension")
    adapter = args.get("adapter")

    modes_set = sum(
        [1 if verb else 0, 1 if dimension else 0, 1 if adapter else 0]
    )
    if modes_set == 0:
        raise UsageError(
            "scaffold: --verb <name> is required (or --dimension / --adapter "
            "for v0.5.3 plugin scaffolds)."
        )
    if modes_set > 1:
        raise UsageError(
            "ramify: --verb / --dimension / --adapter are mutually exclusive."
        )

    force = bool(args.get("force", False))
    explicit_local = args.get("substrate_local", False)

    if verb:
        substrate_local = _detect_substrate_local(ctx, explicit_local, mode="verb")
        return _run_verb_mode(args, ctx, substrate_local, force)
    if dimension:
        substrate_local = _detect_substrate_local(
            ctx, explicit_local, mode="dimension"
        )
        return _run_dimension_mode(args, ctx, substrate_local, force)
    # adapter
    substrate_local = _detect_substrate_local(
        ctx, explicit_local, mode="adapter"
    )
    return _run_adapter_mode(args, ctx, substrate_local, force)
