"""Tests for ``myco.meta.scaffold``.

Note: this tests the **v0.5 scaffold verb** (generate stub handler
from a manifest entry). The v0.4 ``tests/test_scaffold.py`` (package-
imports sanity) is a separate, unrelated test file.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from myco.core.context import MycoContext
from myco.core.errors import UsageError
from myco.meta.scaffold import _handler_path, run


def _ctx(root: Path) -> MycoContext:
    return MycoContext.for_testing(root=root)


def test_handler_path_derives_from_handler_string(tmp_path: Path) -> None:
    p = _handler_path("myco.ingestion.xfoo:run", tmp_path)
    assert p == tmp_path / "src" / "myco" / "ingestion" / "xfoo.py"


def test_handler_path_rejects_missing_colon(tmp_path: Path) -> None:
    from myco.core.errors import ContractError

    with pytest.raises(ContractError):
        _handler_path("myco.ingestion.xfoo", tmp_path)


def test_run_refuses_unknown_verb(seeded_substrate: Path) -> None:
    ctx = _ctx(seeded_substrate)
    with pytest.raises(UsageError, match="not declared in manifest"):
        run({"verb": "totally_not_a_verb"}, ctx=ctx)


def test_run_requires_verb(seeded_substrate: Path) -> None:
    ctx = _ctx(seeded_substrate)
    with pytest.raises(UsageError, match="--verb"):
        run({}, ctx=ctx)


def test_run_skips_when_handler_exists(seeded_substrate: Path) -> None:
    """`eat` is a real manifest verb with a real handler at
    ``src/myco/ingestion/eat.py``. Scaffold should detect the file
    exists and refuse to overwrite without ``--force``."""
    # Fake the filesystem shape: create the handler file relative to
    # the seeded substrate root so scaffold sees it as present.
    target = seeded_substrate / "src" / "myco" / "ingestion" / "eat.py"
    target.parent.mkdir(parents=True)
    target.write_text("existing handler\n", encoding="utf-8")

    ctx = _ctx(seeded_substrate)
    r = run({"verb": "eat"}, ctx=ctx)
    assert r.exit_code == 0
    assert r.payload["written"] is False
    # File content preserved.
    assert target.read_text(encoding="utf-8") == "existing handler\n"


def test_run_writes_stub(seeded_substrate: Path) -> None:
    """Scaffold `distill` into a fresh substrate root (no existing
    handler file). The written stub returns a well-formed Result."""
    ctx = _ctx(seeded_substrate)
    r = run({"verb": "distill"}, ctx=ctx)
    assert r.exit_code == 0
    assert r.payload["written"] is True
    target = seeded_substrate / "src" / "myco" / "digestion" / "distill.py"
    assert target.is_file()
    body = target.read_text(encoding="utf-8")
    assert "stub handler generated by `myco scaffold`" in body
    assert "def run(args" in body
    assert "\"stub\": True" in body
    assert "\"verb\": \"distill\"" in body


def test_run_force_overwrites(seeded_substrate: Path) -> None:
    target = seeded_substrate / "src" / "myco" / "digestion" / "reflect.py"
    target.parent.mkdir(parents=True)
    target.write_text("old content\n", encoding="utf-8")

    ctx = _ctx(seeded_substrate)
    r = run({"verb": "reflect", "force": True}, ctx=ctx)
    assert r.payload["written"] is True
    assert r.payload["overwritten"] is True
    body = target.read_text(encoding="utf-8")
    assert "stub handler generated by `myco scaffold`" in body
    assert "old content" not in body
